### ISSUE TITLE
Change delimiter

### ISSUE THREAD

**Issue by 1dot44mb** [dpaquette/EntityFramework.Seeder#5]
Hi,

Can we change the delimiter used in parsing the CSV file?
CSVHelper has this method: 
```
csv.Configuration.Delimiter = ",";
```

Can you expose it so we can configure it?

Thanks.

**Comment by dpaquette** [comment]
I will take a look. That definitely should be easy to do

**Comment by 1dot44mb** [comment]
Thanks. Actually there are other things that CsvHelper does too. Better expose whole class so that users freely configure if they want to.

**Comment by dpaquette** [comment]
Yeah, I was thinking of exposing the whole configuration class. I will get to this sometime this week. Of course, Pull Requests are welcome if you want to give it a try yourself.

**Comment by dpaquette** [comment]
All options are now available via Seeder.Configuration. See project readme for details. Thanks for the idea!

**Comment by mtozlu** [comment]
Thank you for implementing it.
